### ISSUE TITLE
2 suggestions

### ISSUE THREAD

**Issue by OhSoGood** [aceindy/DesktopIconsSaveRestoreTool#1]
Hi
Nice improvments over the original code. Thanks. Here are 2 suggestions I would raise in Program.cs:
```
public static string PathWithEnv = @"%LOCALAPPDATA%\DesktopIcons";
public static string Defaultfilename = PathWithEnv + @"\desktop.xml"; 
```
=> use LocalAppData instead of My Documents, and make one constant use the other to avoid doublon.
Just my 2 cents!

**Comment by OhSoGood** [comment]
And a bug fix: in IconSaveRestore, line 15 should use Environment.ExpandEnvironmentVariables and so becomes:
`var cname = Environment.ExpandEnvironmentVariables(Program.GetWindowsRegistry());`

**Comment by aceindy** [comment]
Done
https://github.com/aceindy/DesktopIconsSaveRestoreTool/commit/6011605d8b0ac0cd634252c1853e100cf0da159b
